webui/webui/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import SubmitField

class VideoForm(FlaskForm):
    video = FileField(validators=[FileRequired(u'請選擇影片')], render_kw={'style': 'display:none'})
    submit = SubmitField(u'上傳', render_kw={'class': 'btn btn-jelly normal-btn loading'})

webui/webui/__init__.py
import os
from flask import Flask, render_template
from flask_uploads import configure_uploads, patch_request_class

from webui.setting import config
from webui.blueprints.webui import webui_bp
from webui.extensions import facials, actions


def create_app(config_name=None):
    if config_name is None:
        config_name = os.getenv('FLASK_CONFIG', 'development')

    app = Flask('webui')
    app.config.from_object(config[config_name])

    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True

    register_extensions(app)
    register_blueprints(app)
    register_errors(app)
    return app


def register_extensions(app):
    # upload config
    configure_uploads(app, facials)
    configure_uploads(app, actions)
    patch_request_class(app, 1024 * 1024 * 1024)  # default maximum file size is 16MB


def register_blueprints(app):
    app.register_blueprint(webui_bp)


def register_errors(app):
    # invalid route
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('error.html', error=['Page Not Found', '此頁面不存在']), 404

    # server error
    @app.errorhandler(500)
    def internal_server_error(e):
        return render_template('error.html', error=['Internal Server Error', '伺服器發生錯誤']), 500

webui/webui/blueprints/webui.py
import os
import gc
from datetime import datetime
from subprocess import Popen
import multiprocessing as mp
import time
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, jsonify, Response

from webui.extensions import facials, actions
from webui.forms import VideoForm
from webui.facial_camera import VideoCamera

webui_bp = Blueprint('webui', __name__)


def getFiles(path=None):
    files = os.listdir(path)
    files = [list(os.path.splitext(file))+[datetime.fromtimestamp(os.path.getctime(os.path.join(path, file))).strftime("%Y/%m/%d - %H:%M:%S")] for file in files]
    files.sort(key = lambda files: files[2])
    return files


def getAbsPath(path=None):
    basedir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
    path = os.path.join(basedir, path)
    return path


def gen(camera):
    try:
        while True:
            # print('dalao')
            frame = camera.get_frame()
            yield (b'--frame\r\n'
                 b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
    except Exception as e:
        print(e)
        print('deleted')
        # del camera
        



@webui_bp.route('/', methods=('GET', 'POST'))
def index():
    return render_template('index.html')


@webui_bp.route('/camera')
def camera():
    return render_template('camera.html')


@webui_bp.route('/facial', methods=('GET', 'POST'))
def facial():
    # global camera 
    # camera.__del__()
    # print(id(camera))
    # del camera
    # gc.collect()
    form = VideoForm()

    if request.method == 'POST':
        video = request.files['video']
        facials.save(video)
        # set args
        source = facials.path(video.filename)
        dest = facials.path(video.filename).replace('.mp4', '_predicted.mp4')
        model = getAbsPath('emotion_classifier.h5')

        p = Popen('python3 webui/facial_video.py -v {} -r {} -m {}'.format(source, dest, model), shell=True)
        p.wait()

        url = facials.url(video.filename.replace('.mp4', '_predicted.mp4'))
        return url
    return render_template('facial.html', form=form, postURL=url_for('webui.facial'), filesURL=url_for('webui.facialfiles'))


@webui_bp.route('/action', methods=('GET', 'POST'))
def action():
    form = VideoForm()
    if request.method == 'POST':
        video = request.files['video']
        actions.save(video)

        # set args
        source = actions.path(video.filename)
        # dest = actions.path(video.filename).replace('.mp4', '_predicted.mp4')
        # model = getAbsPath('')
        path = getAbsPath('st-gcn/main2.py')
        config = getAbsPath('st-gcn/config/st_gcn/childrenAct/childrenAct_recognize_1frame_4type_j.yaml')
        p = Popen('python3  {} --video {} --config {} --frame_segment 1'.format(path, source, config), shell=True)
        p.wait()

        url = actions.url(video.filename.replace('.mp4', '_predicted.mp4'))
        return url
    return render_template('action.html', form=form, postURL=url_for('webui.action'), filesURL=url_for('webui.actionfiles'))

@webui_bp.route('/members', methods=('GET', 'POST'))
def members():
    return render_template('members.html')


@webui_bp.route('/facialfiles', methods=('GET', 'POST'))
def facialfiles():
    path = current_app.config['UPLOADED_FACIALS_DEST']
    files = getFiles(path)
    return render_template('files.html', fileset=facials, files=files)


@webui_bp.route('/actionfiles', methods=('GET', 'POST'))
def actionfiles():
    path = current_app.config['UPLOADED_ACTIONS_DEST']
    files = getFiles(path)
    return render_template('files.html', fileset=actions, files=files)

@webui_bp.route('/stream')
def stream():
    path = getAbsPath('emotion_classifier.h5')
    camera = VideoCamera(path)

    # camera
    # print(id(camera))

    return Response(gen(camera), mimetype='multipart/x-mixed-replace; boundary=frame')

webui/webui/st-gcn/feeder/__init__.py
from . import tools

webui/webui/st-gcn/main.py
#!/usr/bin/env python
import argparse
import sys

# torchlight
import torchlight
from torchlight import import_class

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Processor collection')

    # region register processor yapf: disable
    processors = dict()
    processors['recognition'] = import_class('processor.recognition.REC_Processor')
    processors['demo'] = import_class('processor.demo.Demo')
    #endregion yapf: enable

    # add sub-parser
    subparsers = parser.add_subparsers(dest='processor')
    for k, p in processors.items():
        subparsers.add_parser(k, parents=[p.get_parser()])

    # read arguments
    arg = parser.parse_args()

    # start
    Processor = processors[arg.processor]
    p = Processor(sys.argv[2:])

    p.start()
    # p.start_frame()

webui/webui/st-gcn/net/__init__.py
from . import utils

webui/webui/st-gcn/tools/__init__.py
from . import utils

webui/webui/st-gcn/tools/utils/__init__.py
from . import video
from . import video_to_skeleton
from . import openpose
from . import visualization

webui/webui/st-gcn/torchlight/torchlight/__init__.py
from .io import IO
from .io import str2bool
from .io import str2dict
from .io import DictAction
from .io import import_class
from .gpu import visible_gpu
from .gpu import occupy_gpu
from .gpu import ngpu

webui/webui/templates/_modal.html
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="embed-responsive embed-responsive-16by9">
        <video controls class="embed-responsive-item">
          <source src="" type="video/mp4">
        </video>
      </div>
    </div>
  </div>
</div>

webui/webui/templates/_site-section.html
<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="section-title">
          <h2>選擇檔案</h2>
        </div>
        <div class="post-entry-2 d-flex col" style="margin-bottom:1em ">
          <div class="thumbnail">
            <img src="{{ url_for('static', filename='images/upload.png') }}" alt="Example" width="30%" height="30%"
              style="display: block; margin: auto;margin-top: 20%; width: 18%; height: 30%;">

          </div>
          <div class="contents">
            <p class="mb-3">選擇這部電腦上的檔案進行分析</p>
            <div class="col">
              <div class="row" style="margin-bottom:1em;">
                <div class="col-3 text-center"
                  style="background: rgb(248, 248, 248); font-weight: 500; color:rgb(60, 60, 60); letter-spacing: 2px;">
                  檔名</div>
                <div id="file-name" class="col-9"
                  style="color: gray ; border: 0.5px 0.5px 0.5px 0 rgb(248,248,248) solid;">尚未選擇</div>
              </div>
            </div>


          </div>
        </div>
        <div class="col">
          <form method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="row justify-content-md-center">
              <div class="col-4">

                <label class="btn btn-jelly normal-btn">
                  {{ form.video }}
                  <span>選擇影片</span>
                </label>

              </div>
              <div class="col-4">
                {{ form.submit }}
              </div>

            </div>

          </form>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="section-title">
          <h2>瀏覽結果</h2>
        </div>
        <div class="post-entry-2 d-flex">
          <div class="thumbnail">
            <img src="{{ url_for('static', filename='images/search.png') }}" alt="Example" width="30%" height="30%"
              style="display: block; margin: auto;margin-top: 20%; width: 18%; height: 30%;">

          </div>
          <div class="contents">
            <p class="mb-3">觀看分析完成的影片</p>
            <h2><a class="btn btn-jelly normal-btn" href="{{ filesURL }}" style="color: white;">點此瀏覽結果</a></h2>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% include '_modal.html' %}

{% block javascript %}
<script>
  $('#video').parent().click(function () {
    $('#video').change(function () {
      $('#view-result').fadeOut();
      $('.md-auto').removeClass('flow-bg-active').addClass('flow-bg').find('p').removeClass('flow-text-active').addClass('flow-text')
      $('.step-two').removeClass('spinner-border spinner-border-sm').text('❷');

      $('.md-auto').eq(0).removeClass('flow-bg').addClass('flow-bg-active')
        .find('p').removeClass('flow-text').addClass('flow-text-active')

      filename = $(this).val().replace(/.*(\/|\\)/, '')
      if (filename != '') {
        $('#file-name').text(filename)
      }
      else {
        $('#file-name').text('尚未選擇')
      }
    })
  })

  $('form').submit(function (e) {
    e.preventDefault()
    data = new FormData($('form')[0])
    $.ajax({
      type: 'POST',
      url: '{{ postURL }}',
      data: data,
      contentType: false,
      cache: false,
      processData: false,
      beforeSend: function () {
        $('.md-auto').removeClass('flow-bg-active').addClass('flow-bg')
          .find('p').removeClass('flow-text-active').addClass('flow-text')
        $('.md-auto').eq(1).removeClass('flow-bg').addClass('flow-bg-active').find('p').removeClass('flow-text').addClass('flow-text-active')
        $('.step-two').text('').addClass('spinner-border spinner-border-sm');
      },
      success: function (msg) {
        $('.md-auto').removeClass('flow-bg-active').addClass('flow-bg')
          .find('p').removeClass('flow-text-active').addClass('flow-text')
        $('.step-two').removeClass('spinner-border spinner-border-sm').text('❷');

        $('#view-result').fadeIn();
        $('.md-auto').eq(2).removeClass('flow-bg').addClass('flow-bg-active')
          .find('p').removeClass('flow-text').addClass('flow-text-active')

        
        $('source').attr({ 'src': msg })
        $("video")[0].load();
      }
    })
  })
</script>
{% endblock %}

webui/webui/templates/_step.html
<div class="col" style="margin-top: 4em;">
  <div class="row">
    <div class="col md-auto flow-bg-active">
      <p class="text-center flow-text-active">❶ 選擇影片</p>
    </div>
    <div class="col md-auto flow-bg">
      <p class="text-center flow-text"><span class="step-two">❷</span> 分析中</p>
    </div>
    <div class="col md-auto flow-bg">
      <p class="text-center flow-text">❸ 分析完成</p>
    </div>
  </div>
  <div id="view-result" class="col" style="margin-top: 1em;">
    <p class="mb-3 text-center" style="font-weight: 500;">點擊下方按鈕觀看</p>
    <div class="row justify-content-md-center">
      <div class="col col-3 flow-play">
        <a href="#" data-toggle="modal" data-target=".bd-example-modal-lg">
          <p class="text-center flow-text" style="color: white;">➤ 觀看結果</p>
        </a>
      </div>
    </div>
  </div>

</div>

webui/webui/templates/action.html
{% extends 'base.html' %}

{% block content %}
<div class="py-0">
  <div class="container">
    <div class="half-post-entry d-block d-lg-flex bg-light">
      <div class="contents col-8">
        <span class="caption">ACTION RECOGNITION</span>
        <h2 style="color:rgb(20, 20, 20)">行為偵測</h2>
        <p class="mb-3">分析幼童在校動作</p>
      </div>
    </div>
    {% include '_step.html' %}
  </div>
</div>
{% include '_site-section.html' %}
{% endblock %}

webui/webui/templates/base.html
<!DOCTYPE html>
<html lang="zh-tw">

<head>
  {% block head %}
  <title>{% block title %}幼兒表情辨識與行為偵測{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=B612+Mono|Cabin:400,700&display=swap" rel="stylesheet">

  <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/jquery-ui.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/jquery.fancybox.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/aos.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/effect.css') }}" rel="stylesheet">
  {% endblock head %}
  
  <!-- loader -->
  {% block scripts %}
  <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#ff5e15"/></svg></div>
  <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-migrate-3.0.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-ui.js') }}"></script>
  <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.stellar.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.countdown.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.easing.1.3.js') }}"></script>
  <script src="{{ url_for('static', filename='js/aos.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.fancybox.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.sticky.js') }}"></script>
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  {% endblock %}
 {% block javascript %}{% endblock %}
</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

  <!-- site-wrap -->
  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>

    <div class="header-top">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12 col-lg-6 d-flex">
            <a href="{{ url_for('webui.index') }}" class="site-logo" style="font-weight: 500;color: rgb(50,50,50); letter-spacing: 1px;">
              幼兒表情辨識與行為偵測
            </a>
            <a href="#" class="ml-auto d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black"><span
                class="icon-menu h3"></span></a>
          </div>
          
          <div class="col-6 d-block d-lg-none text-right">
            
          </div>
        </div>
      </div>

      <div class="site-navbar py-2 js-sticky-header site-navbar-target d-none pl-0 d-lg-block" role="banner">

      <div class="container">
        <div class="d-flex align-items-center">
          
          <div class="mr-auto">
            <nav class="site-navigation position-relative text-right" role="navigation">
              <ul class="site-menu main-menu js-clone-nav mr-auto d-none pl-0 d-lg-block">
                <li class="active">
                  <a href="{{ url_for('webui.index') }}" class="nav-link text-left borderCenter">主頁</a>
                </li>
                <li>
                  <a href="{{ url_for('webui.facial') }}" class="nav-link text-left borderCenter">表情辨識</a>
                </li>
                <li>
                  <a href="{{ url_for('webui.action') }}" class="nav-link text-left borderCenter">行為偵測</a>
                </li>
                <li>
                  <a href="{{ url_for('webui.members') }}" class="nav-link text-left borderCenter">小組成員</a>
                </li>
              </ul>                                                                                                                                                                                                                                                                                         
            </nav>

          </div>
         
        </div>
      </div>

    </div>
    <hr>
    <div class="site-section" style="padding:1em 0;">
    </div>

    <!-- page Content -->
    {% block content %}{% endblock %}

    <!-- footer -->
    <div class="footer">
      <div class="container">
        

        <div class="row">
          <div class="col-12">
            <div class="copyright">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>

</html>

webui/webui/templates/error.html
{% extends "base.html" %}

{% block content %}
<div class="py-0">
  <div class="container">
    <div class="half-post-entry d-block d-lg-flex bg-light">
      <div class="contents col">
        <span class="caption">{{ error[0] }}</span>
        <h2 style="color:rgb(20, 20, 20)">{{ error[1] }}</h2>
        <p class="mb-3"><a href="{{ url_for('webui.index') }}">Go Back</a></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

webui/webui/templates/facial.html
{% extends 'base.html' %}

{% block content %}
<div class="py-0">
  <div class="container">
    <div class="half-post-entry d-block d-lg-flex bg-light">
      <div class="contents col">
        <span class="caption">Facial Expression</span>
        <h2 style="color:rgb(20, 20, 20)">表情辨識</h2>
        <p class="mb-3">觀察幼童在校表情</p>
      </div>
    </div>
    {% include '_step.html' %}
  </div>
</div>
{% include '_site-section.html' %}
{% endblock %}

webui/webui/templates/files.html
{% extends 'base.html' %}

{% block content %}
<div class="site-section" style="padding-top: 1em;">
  <div class="container">
    <div class="col">
      <table class="table ">
        <thead style="background: rgb(248,248,248);">
          <tr>
            <th scope="col">編號</th>
            <th scope="col">影片名稱</th>
            <th scope="col">影片類型</th>
            <th scope="col">建立時間</th>
            <th scope="col">操作</th>
          </tr>
        </thead>
        <tbody>
          {% for file in files %}
          <tr>
              <th scope="row"><p class="table-name index-number">{{ loop.index }}</p></th>
              <td><p class="table-name">{{ file[0] }}</p></td>
              <td><div class="row justify-content-center"><div class="col col-7"><p class="table-name file-type text-center">{{ file[1][1:].upper() }}</p></div></div></td>
              <td><p class="table-name text-center">{{ file[2] }}</p></td>
              <!-- <td><div class="col text-center"><button type="submit" class="btn btn-jelly normal-btn md-auto" data-toggle="modal" data-target=".bd-example-modal-lg" onclick="showVideo('{{ fileset.url(file[0]+file[1]) }}')">▶</button></div></td> -->
              <td><div class="col text-center"><button type="submit" class="play-btn md-auto" data-toggle="modal" data-target=".bd-example-modal-lg" onclick="showVideo('{{ fileset.url(file[0]+file[1]) }}')">播放</button></div></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% include '_modal.html' %}
{% endblock %}

{% block javascript %}
<script>
  function showVideo(src) {
    $('source').attr({'src': src})
    $("video")[0].load();
  }
</script>
{% endblock %}

webui/webui/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="py-0">
  <div id="gosh" class="container" style="position: relative; padding: 0;">
    <img src="{{ url_for('static', filename='images/white.jpg') }}" class="img-fluid" width="100%" style="opacity: 0;">
    <img id="stream" src="{{ url_for('webui.stream') }}" class="img-fluid" width="100%">
    <div class="in-video half-post-entry d-block d-lg-flex bg-light">
      <div class="contents text-center border-right">
        <span class="caption">Facial Expression</span>
        <h2>表情辨識</h2>
        <p class="mb-3">觀察幼童在校表情</p>
        <div class="row justify-content-md-center">
          <div class="col-md-auto">
            <a class="btn py-3 px-5 btn-jelly" href="{{ url_for('webui.facial') }}"
              style="color: white; margin-top: 1em;">前往表情辨識</a>
          </div>
        </div>
      </div>
      <div class="contents text-center">
        <span class="caption">Action Recognition</span>
        <h2 style>行為偵測</h2>
        <p class="mb-3">分析幼童在校動作</p>
        <div class="row justify-content-md-center">
          <div class="col-md-auto">
            <a class="btn py-3 px-5 btn-jelly" href="{{ url_for('webui.action') }}"
              style="color: white; margin-top: 1em;">前往行為偵測</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="site-section" style="padding:2em 0;">
</div>
{% include '_modal.html' %}
{% endblock %}

{% block javascript %}
<script>
  $(function() {
    // flag = false
    $('.in-video').hide()
    $('#gosh').mouseenter(function() {
      
      $('.in-video').fadeTo(400, 0.8)
    })
    $('#gosh').mouseleave(function() {
    
      $('.in-video').fadeTo(400, 0)
    })
  })
</script>
{% endblock %}

webui/webui/templates/members.html
{% extends 'base.html' %}

{% block content %}
<div class="py-0">
  <div class="container">
    <div class="half-post-entry d-block d-lg-flex bg-light">
      <div class="contents col-8">
        <span class="caption">Group Member</span>
        <h2 style="color:rgb(20, 20, 20)">小組成員</h2>

      </div>

    </div>
    <div class="col" style="margin-top: 2em;">
      <div class="trend-entry d-flex">
        <div class="number align-self-start" style="color: #FF7C83;font-weight: 400;">01</div>
        <div class="trend-contents col">
          <div class="col">
            <h2 style="color: rgb(30, 30, 30)">劉 凱翔</h2>
            <div class="post-meta">
              <span class="date-read">B10517030<span class="mx-1">
            </div>
          </div>

          <hr style="margin: 10px 0;">
          <div class="col">
            <span class="d-block">行為分析 &bullet; 資料集整理</span>
          </div>
        </div>
      </div>
      <div class="trend-entry d-flex">
        <div class="number align-self-start" style="color: #FF516B;font-weight: 400;">02</div>
        <div class="trend-contents col">
          <div class="col">
            <h2 style="color: rgb(30, 30, 30) ;">姜 典昀</h2>
            <div class="post-meta">
              <span class="date-read">B10517029<span class="mx-1">
            </div>
          </div>

          <hr style="margin: 10px 0;">
          <div class="col">
            <span class="d-block">臉部表情 &bullet; 資料集整理</span>
          </div>
        </div>
      </div>
      <div class="trend-entry d-flex">
        <div class="number align-self-start" style="color: #FF7C83;font-weight: 400;">03</div>
        <div class="trend-contents col">
          <div class="col">
            <h2 style="color: rgb(30, 30, 30) ;">徐 唯毓</h2>
            <div class="post-meta">
              <span class="date-read">B10517045<span class="mx-1">
            </div>
          </div>

          <hr style="margin: 10px 0;">
          <div class="col">
            <span class="d-block">臉部表情 &bullet; 後端處理</span>
          </div>
        </div>
      </div>
      <div class="trend-entry d-flex">
        <div class="number align-self-start" style="color: #FF516B;font-weight: 400;">04</div>
        <div class="trend-contents col">
          <div class="col">
            <h2 style="color: rgb(30, 30, 30) ;">季 成寯</h2>
            <div class="post-meta">
              <span class="date-read">B10523042<span class="mx-1">
            </div>
          </div>

          <hr style="margin: 10px 0;">
          <div class="col">
            <span class="d-block">行為分析 &bullet; 前端設計</span>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>
{% endblock %}